<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AssinadorSIG</AssemblyName>
    <RootNamespace>SigAssinador</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Version>0.4.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PDFsharp-GDI" Version="6.2.4" />
    <PackageReference Include="PdfiumViewer.Updated" Version="2.14.5" />
    <PackageReference Include="PdfiumViewer.Native.x86_64.no_v8-no_xfa" Version="2018.3.18.254" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="8.0.1" />
  </ItemGroup>
</Project>
